export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
        USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
        IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    },

    post: {
        DATA_FETCHING: "POST_DATA_FETCHING",
        DATA_FETCHED: "POST_DATA_FETCHED",
        DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
        DATA_EDITED: "POST_DATA_EDITED",
        POST_DELETED: "POST_DATA_DELETED",
        POST_LIKED: "POST_LIKED",
        POST_COMMENTED: "POST_COMMENTED",
    },
};
