import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { dbConnect } from "@/services/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
